language: php

env:
  global:
    - setup=stable
    - DB_USERNAME=root
    - DB_PASSWORD=

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COVERAGE=1
    - php: 7.2
      env: setup=lowest COVERAGE=0
    - php: 7.1
      env: COVERAGE=0
    - php: 7.1
      env: setup=lowest COVERAGE=0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:

before_install:
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE EloquentFormsTest;'

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - if [ "$COVERAGE" == "1" ]; then vendor/bin/phpunit --coverage-clover /home/travis/clover.xml; fi
  - if [ "$COVERAGE" == "0" ]; then vendor/bin/phpunit; fi

after_script:
  - ./cc-test-reporter format-coverage /home/travis/clover.xml --input-type clover --output /home/travis/clover.json
  - ./cc-test-reporter upload-coverage -i /home/travis/clover.json -r $CC_TEST_REPORTER_ID
